# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
