# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0002_auto_20171007_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
